---
- name: Install docker
  hosts: all
  remote_user: root
  vars:
    - docker_package: "docker"
  pre_tasks:
    - name: Run the equivalent of "pacman -Syu" as a separate step
      community.general.pacman:
        update_cache: yes
    - name: Start and Enable iptables
      ansible.builtin.systemd:
        state: started
        name: iptables
        enabled: yes
  roles:
    - geerlingguy.docker
